package com.minhagasosa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ABASTECIMENTO.
 */
public class Abastecimento {

    private Long id;
    private java.util.Date dataAbastecimento;
    private Float precoTotal;
    private Float precoCombustivel;
    private Float litros;
    private Float odometro;
    private Boolean tanqueCheio;

    public Abastecimento() {
    }

    public Abastecimento(Long id) {
        this.id = id;
    }

    public Abastecimento(Long id, java.util.Date dataAbastecimento, Float precoTotal, Float precoCombustivel, Float litros, Float odometro, Boolean tanqueCheio) {
        this.id = id;
        this.dataAbastecimento = dataAbastecimento;
        this.precoTotal = precoTotal;
        this.precoCombustivel = precoCombustivel;
        this.litros = litros;
        this.odometro = odometro;
        this.tanqueCheio = tanqueCheio;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDataAbastecimento() {
        return dataAbastecimento;
    }

    public void setDataAbastecimento(java.util.Date dataAbastecimento) {
        this.dataAbastecimento = dataAbastecimento;
    }

    public Float getPrecoTotal() {
        return precoTotal;
    }

    public void setPrecoTotal(Float precoTotal) {
        this.precoTotal = precoTotal;
    }

    public Float getPrecoCombustivel() {
        return precoCombustivel;
    }

    public void setPrecoCombustivel(Float precoCombustivel) {
        this.precoCombustivel = precoCombustivel;
    }

    public Float getLitros() {
        return litros;
    }

    public void setLitros(Float litros) {
        this.litros = litros;
    }

    public Float getOdometro() {
        return odometro;
    }

    public void setOdometro(Float odometro) {
        this.odometro = odometro;
    }

    public Boolean getTanqueCheio() {
        return tanqueCheio;
    }

    public void setTanqueCheio(Boolean tanqueCheio) {
        this.tanqueCheio = tanqueCheio;
    }

}
