package com.minhagasosa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.Date;

/**
 * Entity mapped to table "ROTA".
 */
public class Rota {

    private Long id;
    private String Nome;
    private Boolean idaEVolta;
    private Float distanciaIda;
    private Float distanciaVolta;
    private Boolean repeteSemana;
    private Integer repetoicoes;
    private Boolean deRotina;
    private long data;

    public Rota() {
    }

    public Rota(Long id) {
        this.id = id;
    }

    public Rota(Long id, String Nome, Boolean idaEVolta, Float distanciaIda, Float distanciaVolta, Boolean repeteSemana, Integer repetoicoes, Boolean deRotina, long date) {
        this.id = id;
        this.Nome = Nome;
        this.idaEVolta = idaEVolta;
        this.distanciaIda = distanciaIda;
        this.distanciaVolta = distanciaVolta;
        this.repeteSemana = repeteSemana;
        this.repetoicoes = repetoicoes;
        this.deRotina = deRotina;
        this.data = date;//new Date();
    }

    public final Long getId() {
        return id;
    }

    public final void setId(Long id) {
        this.id = id;
    }

    public final String getNome() {
        return Nome;
    }

    public final void setNome(String Nome) {
        this.Nome = Nome;
    }

    public final Boolean getIdaEVolta() {
        return idaEVolta;
    }

    public final void setIdaEVolta(Boolean idaEVolta) {
        this.idaEVolta = idaEVolta;
    }

    public final Float getDistanciaIda() {
        return distanciaIda;
    }

    public final void setDistanciaIda(Float distanciaIda) {
        this.distanciaIda = distanciaIda;
    }

    public final Float getDistanciaVolta() {
        return distanciaVolta;
    }

    public final void setDistanciaVolta(Float distanciaVolta) {
        this.distanciaVolta = distanciaVolta;
    }

    public final Boolean getRepeteSemana() {
        return repeteSemana;
    }

    public final void setRepeteSemana(Boolean repeteSemana) {
        this.repeteSemana = repeteSemana;
    }

    public final Integer getRepetoicoes() {
        return repetoicoes;
    }

    public final void setRepetoicoes(Integer repetoicoes) {
        this.repetoicoes = repetoicoes;
    }

    public final Boolean getDeRotina() {
        return deRotina;
    }

    public final void setDeRotina(Boolean deRotina) {
        this.deRotina = deRotina;
    }

    public final void setData(long data){ this.data = data; }

    public final long getDataInLong() { return  data; }
    public final Date getData() { return  new Date(data); }
}
